# Generated by Django 4.2.20 on 2025-04-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(default='Nom inconnu', max_length=100)),
                ('description', models.TextField(default='Aucune description fournie')),
                ('image', models.CharField(default='Image inconnue', max_length=100)),
            ],
        ),
    ]
