# Generated by Django 4.2.20 on 2025-04-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plat',
            name='plate',
            field=models.CharField(max_length=100),
        ),
    ]
